fix(restart-pipeline) : CheckPrecondition doesn't evaluate expression correctly when upstream stages get restarted
spinnaker/orca pull request #4278
Opened 2022-06-21 17:05 UTC by rjalander

This PR includes the changes to fix the [issue #6675](https://github.com/spinnaker/spinnaker/issues/6675) 

**Root cause:** 
Expression is not considered during restart of pipeline instead it picks the expression result from the previous run
**Fix:** 
Updating `StageExecution` for stage type `checkPreconditions` with expression from `restartDetails` Map
and store the updated `stage` with expression in the `ExecutionRepository`, from where the restart data gets picked.

This PR changes are dependent on https://github.com/spinnaker/gate/pull/1560

2022-06-22 14:01 UTC, mattgogerly requested changes

2022-06-22 14:02 UTC, mattgogerly commented
Are there any tests you can add to validate that this fixes the problem you were seeing?

2022-06-22 15:22 UTC, rjalander commented on orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/CompoundExecutionOperator.java
> +    if (!pipelineStageMap.isEmpty() && pipelineStageMap != null) {
Oh yeah, I missed it here.

2022-06-22 15:23 UTC, rjalander commented on orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/CompoundExecutionOperator.java
> +    List<Map> preconditionList = new ArrayList();
Done

2022-07-12 15:31 UTC, rjalander commented
@mattgogerly any idea how can we fix this check (Queue: Embarked in merge train) for merge.
I created the other PR (https://github.com/spinnaker/gate/pull/1560) with the same privileges and that PR passed this check (https://github.com/spinnaker/gate/runs/7301756832)

2022-07-12 16:33 UTC, andrew-est commented
Adding comment so that I become a participant as I think that may let me have options as @Nordix user

2022-07-12 16:36 UTC, dbyron-sf commented
That check is failing with this message:
<img width="569" alt="image" src="https://user-images.githubusercontent.com/82477955/178546170-e1b28203-0d81-42a9-a267-c8dd344b336b.png">

2022-07-12 16:59 UTC, andrew-est commented
The problem is we can't make the changes to follow the instructions and I think this is related to the issue raised in this discussion
https://github.com/github-community/community/discussions/5634

2022-07-13 19:10 UTC, mattgogerly commented
If you're not able to make the changes to the config are you able to resubmit the PR from a different account?

2022-07-14 16:40 UTC, merged