fix(timeout): Added feature flag for rollback timeout ui input.
spinnaker/orca pull request #4383
Opened 2023-01-31 16:53 UTC by DanielaS12

Feature was tested in previous pr. Adding feature flag.

2023-01-31 17:09 UTC, kkotula commented on orca-clouddriver/src/main/java/com/netflix/spinnaker/orca/clouddriver/tasks/cluster/DetermineRollbackCandidatesTask.java
> +  @Value("${rollback.timeout.enabled:false}")
The name of this property could be confusing to users and developers. It looks like the timeout functionality would be disabled completely if the flag is set to false or not set at all. Would it make sense to rename it to something like `rollback.dynamic-timeout.enabled` ?

2023-01-31 17:14 UTC, kkotula commented on orca-clouddriver/src/main/java/com/netflix/spinnaker/orca/clouddriver/tasks/cluster/DetermineRollbackCandidatesTask.java
> +    if (stageRollbackTimeout) {
To improve expressiveness and simplicity, we could do something like:
``` java
var shouldUseStageRollbackTimeout = stageRollbackTimeout
 && stage.getContext().containsKey("rollbackTimeout");

if (shouldUseStageRollbackTimeout){
    return TimeUnit.MINUTES....
}
return getTimeout();
```

It's a matter of taste though, so feel free to ignore this comment.

2023-01-31 17:24 UTC, ovidiupopa07 requested changes
Let's also add a unit test to validate the feature flag.
One test to validate the functionality if it is enabled and one to check the functionality when it is disabled

2023-01-31 17:24 UTC, ovidiupopa07 commented on orca-clouddriver/src/main/java/com/netflix/spinnaker/orca/clouddriver/tasks/cluster/DetermineRollbackCandidatesTask.java
> +  private static boolean stageRollbackTimeout;
doesn't need to be static. you can add a new argument to the existing constructor
```
private final boolean dynamicRollbackTimeoutEnabled;

  @Autowired
  public DetermineRollbackCandidatesTask(
      ObjectMapper objectMapper,
      RetrySupport retrySupport,
      CloudDriverService cloudDriverService,
      FeaturesService featuresService,
      @Value("${rollback.timeout.enabled:false}") boolean dynamicRollbackTimeoutEnabled) {
    this.retrySupport = retrySupport;
    this.cloudDriverService = cloudDriverService;
    this.previousImageRollbackSupport =
        new PreviousImageRollbackSupport(
            objectMapper, cloudDriverService, featuresService, retrySupport);
    this.dynamicRollbackTimeoutEnabled = dynamicRollbackTimeoutEnabled;
  }
  ```

2023-02-01 16:45 UTC, ovidiupopa07 commented
And I think we should also document how to enable this feature on the [docs page](https://github.com/spinnaker/spinnaker.io/blob/master/content/en/docs)

2023-02-01 17:33 UTC, ovidiupopa07 approved these changes
LGTM

2023-02-01 18:06 UTC, merged

2023-02-02 08:37 UTC, DanielaS12 commented
@Mergifyio backport release-2.28.x

2023-02-02 13:51 UTC, DanielaS12 commented
@ovidiupopa07 or @dogonthehorizon please backport this pr to 1.28.x

2023-02-02 13:56 UTC, ovidiupopa07 commented
> @ovidiupopa07 or @dogonthehorizon please backport this pr to 1.28.x

waiting for a confirmation from @dogonthehorizon . If everything ok I will backport to 1.27.x, 1.28.x and 1.29.x

2023-02-02 14:37 UTC, ovidiupopa07 commented
@mergify backport release-1.27.x release-1.28.x release-1.29.x