fix(artifacts): Consider artifacts from stages when triggering from a pipeline stage
spinnaker/orca pull request #4568
Opened 2023-10-17 23:10 UTC by sergio-quintero

Follow up to https://github.com/spinnaker/orca/pull/4489

Triggering a pipeline from Pipeline A using the [pipeline stage](https://spinnaker.io/docs/reference/pipeline/stages/#pipeline) where Pipeline B uses BakeManifestStage or DeployManifestStage which rely on expectedArtifacts is broken. [ArtifactUtils](https://github.com/spinnaker/orca/blob/master/orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/util/ArtifactUtils.java#L264-L275) is filtering the expectedArtifacts needed in stages. 

In 1.28, you were able to define expectedArtifacts in Pipeline B, and when you triggered from Pipeline A, Pipeline B was able to resolve the artifacts from Pipeline A. [Passing artifacts between pipelines](https://spinnaker.io/docs/reference/ref-artifacts/in-pipelines/#passing-artifacts-between-pipelines)

2023-10-18 06:44 UTC, jervi approved these changes
Looks good to me! Tagging @xibz as well, since you also showed some interest in this area

2023-10-18 07:28 UTC, xibz requested changes
Looks good! I have some very minor nit comments

2023-10-18 07:28 UTC, xibz commented on orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/DependentPipelineStarter.groovy
> +      //DeployManifestStage in ResolveDeploySourceManifestTask using ManifestEvaluator.getManifestArtifact
```suggestion
      // DeployManifestStage in ResolveDeploySourceManifestTask using ManifestEvaluator.getManifestArtifact
```
nit

2023-10-18 07:28 UTC, xibz commented on orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/DependentPipelineStarter.groovy
> +      // BakeManifestStage in CreateBakeManifestTask using BakeManifestContext for Helm
Are these comments accurate? What I mean is I understand that `Helm` bakes with `inputArtifacts` but other stages like `BakeCloudFoundry` also utilize this?

Can we make this more generic and say something more like

```
// Some bake manifest stages may populate the inputArtifacts array. So we need to look to for those ids as well
```

And we may be able to get rid of the other comments as they seem to be very specific but don't capture the whole picture

2023-10-18 07:28 UTC, xibz commented on orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/DependentPipelineStarter.groovy
> +    def requiredArtifactIds = pipelineConfig.get("stages", []).collectMany { stage ->
Do we need this variable? Can't we just use `expectedArtifactIds` here?

2023-10-18 07:36 UTC, xibz commented on orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/DependentPipelineStarter.groovy
> +      // BakeManifestStage in CreateBakeManifestTask using BakeManifestContext for Helm
Maybe even explain why we are looking for these ids as opposed to the expected artifact. Would be good to just document here saying we dont know how consuming pipelines will utilize artifacts from the parent pipeline, so we rely on any input artifact as opposed to the expected artifact

2023-10-18 16:05 UTC, edgarulg approved these changes
LGTM! but before merging it let's address all comments :)

2023-10-20 20:15 UTC, closed without merging

2023-10-20 20:15 UTC, sergio-quintero commented
Closing this PR because we found more stages with different field names that were not considered in this PR. Adding a list of fields in `DependentPipelineStarter` is not maintainable. Also, if someone creates a plugin with a new Stage that utilizes expectedArtifacts, they can define any field name which will not be included in this class. 

We'll send a new PR with a better fix for this issue.