fix(jenkins): Wrong Job name encoding in query params for Artifacts/Properties
spinnaker/orca pull request #4722
Opened 2024-05-03 11:26 UTC by christosarvanitis

Fixes issue https://github.com/spinnaker/spinnaker/issues/6949 when jobNameAsQueryParameter is enabled and Job Name includes spaces.

Introduced by https://github.com/spinnaker/orca/pull/4661

2024-05-03 14:18 UTC, jasonmcintosh commented
Be nice to get some MockWebServer classes to test these at some point... :P NOT sure if that's viable here.

2024-05-08 20:44 UTC, jasonmcintosh approved these changes

2024-05-08 20:54 UTC, jasonmcintosh commented on orca-igor/src/test/groovy/com/netflix/spinnaker/orca/igor/BuildServiceSpecMock.groovy
> +import static com.github.tomakehurst.wiremock.client.WireMock.*
No wildcard imports please!

2024-05-08 20:55 UTC, jasonmcintosh requested changes
Once wildcard fixed think we can merge this :)

2024-05-09 06:40 UTC, christosarvanitis commented on orca-igor/src/test/groovy/com/netflix/spinnaker/orca/igor/BuildServiceSpecMock.groovy
> +import static com.github.tomakehurst.wiremock.client.WireMock.*
Fixed!

2024-05-09 11:43 UTC, ovidiupopa07 approved these changes

2024-05-09 11:44 UTC, merged

2024-05-09 11:50 UTC, ovidiupopa07 commented
@Mergifyio backport release-1.34.x release-1.33.x release-1.32.x